- hosts: localhost
  vars_files:
    - host_vars/flask.yaml
  gather_facts: true
  roles:
    - role: openstack-common

- hosts: database
  vars_files:
    - host_vars/flask.yaml
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/database.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: flask-2
