--- 
# Docker Installation 
# Add a sleep to allow vm to get setup
- name: Sleep for 60 seconds
  wait_for:
    timeout: 60
#- name: Wait until the lock file is removed
#  wait_for: 
#    path: /var/lib/dpkg/lock-frontend
#- name: Wait until the lock file is removed
#  wait_for: 
#    path: /var/lib/dpkg/lock-frontend
- name: Install pip and neovim
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip', 'neovim']
    #register: apt_status
    state: latest
    install-recommends: no
    update_cache: yes
    #lock_timeout: 240
#  until: apt_status is success
#  delay: 10
#  retries: 10
# sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Update pip
  ansible.builtin.pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip 

# see https://docs.docker.com/engine/install/ubuntu/
- name: Uninstall old versions of docker
  become: yes
  ansible.builtin.apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'python-setuptools', 'software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Docker install - add official GPG key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository and update apt cache
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  become: yes
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  become: yes
  ansible.builtin.pip:
    name: ['docker-compose']
    state: latest

- name: create the docker group
  group: 
    name: docker
    state: present
- name: add user to the docker group
  become: yes
  user:
    name: ubuntu
    group: docker
    append: yes
#- name: Sleep for 30 seconds
#  wait_for:
#    timeout: 30
- name: Ensure docker service is started
  become: yes
  ansible.builtin.systemd:
    state: restarted
    name: docker
#- name: Sleep for 30 seconds
#  wait_for:
#    timeout: 30

